services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    environment:
      - DOCKER_ENV=True
    depends_on:
      - database
    volumes:
      - ./backend/scripts:/app/scripts
      - C:/Users/dtand/Downloads/Wizard101/Photos:/app/scripts/photos
    command: |
      bash -c 'python /app/scripts/automate.py ; python /app/api/server.py ; echo "backend is running" '

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: bash -c 'npm run start'

  database:
    image: mysql:8.3
    ports:
      - "3307:3306"
    env_file:
      - ./backend/.env
