services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - DOCKER_ENV=True
      - MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
      - MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
      - MYSQL_USER=${{ secrets.MYSQL_USER }}
      - MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
      - DB_HOST=${{ secrets.DB_HOST }}
      - DB_USER=${{ secrets.DB_USER }}
      - DB_PASS=${{ secrets.DB_PASS }}
      - DB_NAME=${{ secrets.DB_NAME }}
    depends_on:
      - database
    volumes:
      - ./backend/data:/app/data
      - C:/Users/dtand/Downloads/Wizard101/Photos:/app/data/photos
    command: bash -c '/app/data/init_script.sh'

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    command: bash -c 'npm run start'

  database:
    image: mysql:8.3
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${{ secrets.MYSQL_ROOT_PASSWORD }}
      - MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
      - MYSQL_USER=${{ secrets.MYSQL_USER }}
      - MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}